
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Wick
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();     
        
        simuladores sim = new simuladores();
        sim.setSize(1552, 880);
        sim.setLocation(0,0);
        content.removeAll();
        content.add(sim, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
        
        this.setLocationRelativeTo(this);
        JLabel[] escudos = new JLabel[]{ico0, ico1, ico2, ico3, ico4, ico5, ico6, ico7, ico8, ico9, ico10, ico11, ico12, ico13};
        
        
        for(int i = 0; i < 13; i++){
            String ruta = "src/iconos/LauncherButton" + i + ".png";
            utilidades.SetImageLabel(escudos[i], "src/iconos/LauncherButton" + (i + 0) + ".png");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ico0 = new javax.swing.JLabel();
        ico1 = new javax.swing.JLabel();
        ico2 = new javax.swing.JLabel();
        ico3 = new javax.swing.JLabel();
        ico4 = new javax.swing.JLabel();
        ico5 = new javax.swing.JLabel();
        ico6 = new javax.swing.JLabel();
        ico7 = new javax.swing.JLabel();
        ico8 = new javax.swing.JLabel();
        ico9 = new javax.swing.JLabel();
        ico10 = new javax.swing.JLabel();
        ico11 = new javax.swing.JLabel();
        ico12 = new javax.swing.JLabel();
        ico13 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setPreferredSize(new java.awt.Dimension(1552, 880));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );

        jPanel2.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 1550, 880));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ico0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LauncherButton8.png"))); // NOI18N
        ico0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ico0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ico0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ico0MouseExited(evt);
            }
        });
        jPanel1.add(ico0, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 105, 130));

        ico1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LauncherButton0.png"))); // NOI18N
        ico1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ico1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ico1MouseEntered(evt);
            }
        });
        jPanel1.add(ico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 0, 105, 130));

        ico2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LauncherButton1.png"))); // NOI18N
        ico2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 0, 105, 130));

        ico3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LauncherButton2.png"))); // NOI18N
        ico3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ico3, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 0, 105, 130));

        ico4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LauncherButton3.png"))); // NOI18N
        ico4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ico4, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 0, 105, 130));

        ico5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LauncherButton4.png"))); // NOI18N
        ico5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ico5, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 0, 105, 130));

        ico6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LauncherButton5.png"))); // NOI18N
        ico6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ico6, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 0, 105, 130));

        ico7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LauncherButton6.png"))); // NOI18N
        ico7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ico7, new org.netbeans.lib.awtextra.AbsoluteConstraints(778, 0, 105, 130));

        ico8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LauncherButton7.png"))); // NOI18N
        ico8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ico8, new org.netbeans.lib.awtextra.AbsoluteConstraints(889, 0, 105, 130));

        ico9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LauncherButton13.png"))); // NOI18N
        ico9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ico9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 105, 130));

        ico10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LauncherButton9.png"))); // NOI18N
        ico10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ico10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1111, 0, 105, 130));

        ico11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LauncherButton10.png"))); // NOI18N
        ico11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ico11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1222, 0, 105, 130));

        ico12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LauncherButton11.png"))); // NOI18N
        ico12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ico12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1333, 0, 105, 130));

        ico13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ico13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/LauncherButton12.png"))); // NOI18N
        ico13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ico13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1444, 0, 105, 130));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 1550, 130));

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo/FondoBase.png"))); // NOI18N
        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ico0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico0MouseEntered
        Dimension dimension = new Dimension (20,20);
        utilidades.SetImageLabel(ico0, "src/iconos/LauncherButton0.png", dimension);
        
    }//GEN-LAST:event_ico0MouseEntered

    private void ico0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico0MouseExited
        utilidades.SetImageLabel(ico0,"src/iconos/LauncherButton0.png");
    }//GEN-LAST:event_ico0MouseExited

    private void ico1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ico1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPanel content;
    private javax.swing.JLabel ico0;
    private javax.swing.JLabel ico1;
    private javax.swing.JLabel ico10;
    private javax.swing.JLabel ico11;
    private javax.swing.JLabel ico12;
    private javax.swing.JLabel ico13;
    private javax.swing.JLabel ico2;
    private javax.swing.JLabel ico3;
    private javax.swing.JLabel ico4;
    private javax.swing.JLabel ico5;
    private javax.swing.JLabel ico6;
    private javax.swing.JLabel ico7;
    private javax.swing.JLabel ico8;
    private javax.swing.JLabel ico9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
