/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Wick
 */
public class simuladores extends javax.swing.JPanel {

    /**
     * Creates new form simu
     */
    public simuladores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        embarque = new javax.swing.JLabel();
        protocolo = new javax.swing.JLabel();
        maniobras = new javax.swing.JLabel();
        tipoologia = new javax.swing.JLabel();
        señalizacion = new javax.swing.JLabel();
        rescate = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1552, 880));

        jPanel2.setBackground(new java.awt.Color(10, 38, 72));
        jPanel2.setLayout(new java.awt.GridLayout(2, 3));

        embarque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        embarque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniaturas simuladores/HomeButton0.png"))); // NOI18N
        embarque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        embarque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(embarque);

        protocolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        protocolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniaturas simuladores/HomeButton1.png"))); // NOI18N
        protocolo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(protocolo);

        maniobras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maniobras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniaturas simuladores/HomeButton2.png"))); // NOI18N
        maniobras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(maniobras);

        tipoologia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipoologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniaturas simuladores/HomeButton3.png"))); // NOI18N
        tipoologia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(tipoologia);

        señalizacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        señalizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniaturas simuladores/HomeButton4.png"))); // NOI18N
        señalizacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(señalizacion);

        rescate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rescate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniaturas simuladores/HomeButton5.png"))); // NOI18N
        rescate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(rescate);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel embarque;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel maniobras;
    private javax.swing.JLabel protocolo;
    private javax.swing.JLabel rescate;
    private javax.swing.JLabel señalizacion;
    private javax.swing.JLabel tipoologia;
    // End of variables declaration//GEN-END:variables
}
