
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Wick
 */
public class simuladores extends javax.swing.JPanel {

    static String getString(String titulo) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
        
    public main parent;
    
    public int idgrado;
    
    public simuladores() {
        initComponents();

}

    public void start() throws IOException{
        JLabel[] miniaturas = new JLabel[]{embarque,protocolo,maniobras,tipologia,senalizacion,rescate};
        
        
        for(int i = 0; i < 6; i++){
            utilidades.SetImageLabel(miniaturas[i], utilidades.MiniaturaSimulador(idgrado, i), new Dimension (370, 280));
        }
        
//        ImageIcon[] icons = new ImageIcon[6];
//        MouseListener[] mouseListeners = new MouseListener[6];
//        for (int i = 0; i < icons.length; i++) {
//            icons[i] = new ImageIcon("src/miniaturas simuladores/HomeButton" + i + ".png");
//            final int index = i;
//            mouseListeners[i] = new MouseListener() {
//                @Override
//                public void mouseClicked(MouseEvent e) {}
//
//                @Override
//                public void mousePressed(MouseEvent e) {
//                    Dimension dimension = new Dimension (-10, -10);
//                    try {
//                        utilidades.SetImageLabel(miniaturas[index], utilidades.MiniaturaSimulador(idgrado, 1), dimension);
//                    } catch (IOException ex) {
//                        Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                }
//
//                @Override
//                public void mouseReleased(MouseEvent e) {
//                    Dimension dimension = new Dimension (-5, -5);
//                    utilidades.SetImageLabel(miniaturas[index], "src/miniaturas simuladores/HomeButton" + index + ".png", dimension);
//                }
//
//                @Override
//                public void mouseEntered(MouseEvent e) {
//
//                }
//
//                @Override
//                public void mouseExited(MouseEvent e) {
//                    Dimension dimension = new Dimension (-10, -10);
//                    utilidades.SetImageLabel(miniaturas[index], "src/miniaturas simuladores/HomeButton" + index + ".png", dimension);
//                }
//            };
//            miniaturas[i].addMouseListener(mouseListeners[i]);
//        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        embarque = new javax.swing.JLabel();
        protocolo = new javax.swing.JLabel();
        maniobras = new javax.swing.JLabel();
        tipologia = new javax.swing.JLabel();
        senalizacion = new javax.swing.JLabel();
        rescate = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1552, 880));

        jPanel2.setBackground(new java.awt.Color(10, 38, 72));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        embarque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        embarque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniaturas simuladores/HomeButton0.png"))); // NOI18N
        embarque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        embarque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        embarque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                embarqueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                embarqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                embarqueMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                embarqueMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                embarqueMouseReleased(evt);
            }
        });
        jPanel2.add(embarque, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 380, 291));

        protocolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        protocolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniaturas simuladores/HomeButton1.png"))); // NOI18N
        protocolo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        protocolo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                protocoloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                protocoloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                protocoloMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                protocoloMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                protocoloMouseReleased(evt);
            }
        });
        jPanel2.add(protocolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 380, 291));

        maniobras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maniobras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniaturas simuladores/HomeButton2.png"))); // NOI18N
        maniobras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maniobras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maniobrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maniobrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maniobrasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maniobrasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                maniobrasMouseReleased(evt);
            }
        });
        jPanel2.add(maniobras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, 381, 291));

        tipologia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniaturas simuladores/HomeButton3.png"))); // NOI18N
        tipologia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tipologia.setMaximumSize(new java.awt.Dimension(381, 291));
        tipologia.setMinimumSize(new java.awt.Dimension(381, 291));
        tipologia.setPreferredSize(new java.awt.Dimension(381, 291));
        tipologia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipologiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tipologiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tipologiaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tipologiaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tipologiaMouseReleased(evt);
            }
        });
        jPanel2.add(tipologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 381, 291));

        senalizacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senalizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniaturas simuladores/HomeButton4.png"))); // NOI18N
        senalizacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        senalizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                senalizacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                senalizacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                senalizacionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                senalizacionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                senalizacionMouseReleased(evt);
            }
        });
        jPanel2.add(senalizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 380, 291));

        rescate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rescate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniaturas simuladores/HomeButton5.png"))); // NOI18N
        rescate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rescate.setMaximumSize(new java.awt.Dimension(380, 291));
        rescate.setMinimumSize(new java.awt.Dimension(380, 291));
        rescate.setPreferredSize(new java.awt.Dimension(380, 290));
        rescate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rescateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rescateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rescateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rescateMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rescateMouseReleased(evt);
            }
        });
        jPanel2.add(rescate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 490, 380, 291));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void embarqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_embarqueMouseClicked
   launcher laun;
        try {
            laun = parent.crearLauncher();
            laun.grado=0;
            laun.simulador=0;
            laun.start();
                    parent.paintLauncher(laun);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_embarqueMouseClicked

    private void protocoloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_protocoloMouseClicked
        launcher laun;
        try {           
            laun = parent.crearLauncher();
            laun.grado=0;
            laun.simulador=1;
            laun.start();
                    parent.paintLauncher(laun);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_protocoloMouseClicked

    private void maniobrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maniobrasMouseClicked
        launcher laun;
        try {           
            laun = parent.crearLauncher();
            laun.grado=0;
            laun.simulador=2;
            laun.start();
                    parent.paintLauncher(laun);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_maniobrasMouseClicked

    private void tipologiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipologiaMouseClicked
        launcher laun;
        try {           
            laun = parent.crearLauncher();
            laun.grado=0;
            laun.simulador=3;
            laun.start();
                    parent.paintLauncher(laun);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tipologiaMouseClicked

    private void senalizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_senalizacionMouseClicked
        launcher laun;
        try {           
            laun = parent.crearLauncher();
            laun.grado=0;
            laun.simulador=4;
            laun.start();
                    parent.paintLauncher(laun);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_senalizacionMouseClicked

    private void rescateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rescateMouseClicked
        launcher laun;
        try {           
            laun = parent.crearLauncher();
            laun.grado=0;
            laun.simulador=5;
            laun.start();
                    parent.paintLauncher(laun);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rescateMouseClicked

    private void embarqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_embarqueMouseEntered
        Dimension dimension = new Dimension (-5, -5);
        try {
            utilidades.SetImageLabel(embarque,utilidades.MiniaturaSimulador(idgrado, 0), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_embarqueMouseEntered

    private void embarqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_embarqueMouseExited
        Dimension dimension = new Dimension (-10, -10);
        try {
            utilidades.SetImageLabel(embarque,utilidades.MiniaturaSimulador(idgrado, 0), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_embarqueMouseExited

    private void embarqueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_embarqueMousePressed
        Dimension dimension = new Dimension (-10, -10);
        try {
            utilidades.SetImageLabel(embarque,utilidades.MiniaturaSimulador(idgrado, 0), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_embarqueMousePressed

    private void embarqueMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_embarqueMouseReleased
        Dimension dimension = new Dimension (-5, -5);
        try {
            utilidades.SetImageLabel(embarque,utilidades.MiniaturaSimulador(idgrado, 0), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_embarqueMouseReleased

    private void protocoloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_protocoloMouseEntered
        Dimension dimension = new Dimension (-5, -5);
        try {
            utilidades.SetImageLabel(protocolo,utilidades.MiniaturaSimulador(idgrado, 1), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_protocoloMouseEntered

    private void protocoloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_protocoloMouseExited
        Dimension dimension = new Dimension (-10, -10);
        try {
            utilidades.SetImageLabel(protocolo,utilidades.MiniaturaSimulador(idgrado, 1), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_protocoloMouseExited

    private void protocoloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_protocoloMousePressed
        Dimension dimension = new Dimension (-10, -10);
        try {
            utilidades.SetImageLabel(protocolo,utilidades.MiniaturaSimulador(idgrado, 1), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_protocoloMousePressed

    private void protocoloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_protocoloMouseReleased
        Dimension dimension = new Dimension (-5, -5);
        try {
            utilidades.SetImageLabel(protocolo,utilidades.MiniaturaSimulador(idgrado, 1), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_protocoloMouseReleased

    private void maniobrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maniobrasMouseEntered
        Dimension dimension = new Dimension (-5, -5);
        try {
            utilidades.SetImageLabel(maniobras,utilidades.MiniaturaSimulador(idgrado, 2), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_maniobrasMouseEntered

    private void maniobrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maniobrasMouseExited
        Dimension dimension = new Dimension (-10, -10);
        try {
            utilidades.SetImageLabel(maniobras,utilidades.MiniaturaSimulador(idgrado, 2), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_maniobrasMouseExited

    private void maniobrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maniobrasMousePressed
    Dimension dimension = new Dimension (-10, -10);
        try {
            utilidades.SetImageLabel(maniobras,utilidades.MiniaturaSimulador(idgrado, 2), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_maniobrasMousePressed

    private void maniobrasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maniobrasMouseReleased
        Dimension dimension = new Dimension (-5, -5);
        try {
            utilidades.SetImageLabel(maniobras,utilidades.MiniaturaSimulador(idgrado, 2), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_maniobrasMouseReleased

    private void tipologiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipologiaMouseEntered
        Dimension dimension = new Dimension (-5, -5);
        try {
            utilidades.SetImageLabel(tipologia,utilidades.MiniaturaSimulador(idgrado, 3), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tipologiaMouseEntered

    private void tipologiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipologiaMouseExited
        Dimension dimension = new Dimension (-10, -10);
        try {
            utilidades.SetImageLabel(tipologia,utilidades.MiniaturaSimulador(idgrado, 3), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tipologiaMouseExited

    private void tipologiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipologiaMousePressed
    Dimension dimension = new Dimension (-10, -10);
        try {
            utilidades.SetImageLabel(tipologia,utilidades.MiniaturaSimulador(idgrado, 3), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tipologiaMousePressed

    private void tipologiaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipologiaMouseReleased
        Dimension dimension = new Dimension (-5, -5);
        try {
            utilidades.SetImageLabel(tipologia,utilidades.MiniaturaSimulador(idgrado, 3), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_tipologiaMouseReleased

    private void senalizacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_senalizacionMouseEntered
        Dimension dimension = new Dimension (-5, -5);
        try {
            utilidades.SetImageLabel(senalizacion,utilidades.MiniaturaSimulador(idgrado, 4), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_senalizacionMouseEntered

    private void senalizacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_senalizacionMouseExited
        Dimension dimension = new Dimension (-10, -10);
        try {
            utilidades.SetImageLabel(senalizacion,utilidades.MiniaturaSimulador(idgrado, 4), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_senalizacionMouseExited

    private void senalizacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_senalizacionMousePressed
    Dimension dimension = new Dimension (-10, -10);
        try {
            utilidades.SetImageLabel(senalizacion,utilidades.MiniaturaSimulador(idgrado, 4), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_senalizacionMousePressed

    private void senalizacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_senalizacionMouseReleased
        Dimension dimension = new Dimension (-5, -5);
        try {
            utilidades.SetImageLabel(senalizacion,utilidades.MiniaturaSimulador(idgrado, 4), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_senalizacionMouseReleased

    private void rescateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rescateMouseEntered
        Dimension dimension = new Dimension (-5, -5);
        try {
            utilidades.SetImageLabel(rescate,utilidades.MiniaturaSimulador(idgrado, 5), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rescateMouseEntered

    private void rescateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rescateMouseExited
        Dimension dimension = new Dimension (-10, -10);
        try {
            utilidades.SetImageLabel(rescate,utilidades.MiniaturaSimulador(idgrado, 5), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rescateMouseExited

    private void rescateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rescateMousePressed
    Dimension dimension = new Dimension (-10, -10);
        try {
            utilidades.SetImageLabel(rescate,utilidades.MiniaturaSimulador(idgrado, 5), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rescateMousePressed

    private void rescateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rescateMouseReleased
        Dimension dimension = new Dimension (-5, -5);
        try {
            utilidades.SetImageLabel(rescate,utilidades.MiniaturaSimulador(idgrado, 5), dimension);
        } catch (IOException ex) {
            Logger.getLogger(simuladores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rescateMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel embarque;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel maniobras;
    private javax.swing.JLabel protocolo;
    private javax.swing.JLabel rescate;
    private javax.swing.JLabel senalizacion;
    private javax.swing.JLabel tipologia;
    // End of variables declaration//GEN-END:variables
}
